trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Use_Case7'  # Name of your Azure DevOps service connection
  resourceGroupName: 'myresourcegroup'           # Resource group name
  location: 'EastUS'                             # Azure region
  vmName: 'myVM'                                 # Name of the VM
  vmSize: 'Standard_B1s'                         # VM size
  adminUsername: 'rao900702@gmail.com'                     # Admin username for VM
  adminPassword: 'VRams@#9849'                 # Admin password for VM (Use secret storage in real projects)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Create a resource group
      az group create --name $(resourceGroupName) --location $(location)

      # Create a virtual machine
      az vm create \
        --resource-group $(resourceGroupName) \
        --name $(vmName) \
        --image UbuntuLTS \
        --size $(vmSize) \
        --admin-username $(adminUsername) \
        --admin-password $(adminPassword) \
        --generate-ssh-keys

      # Open port 22 for SSH access
      az vm open-port --port 22 --resource-group $(resourceGroupName) --name $(vmName)
